define [], ()->
    CONSTANTS =
        SCREEN_WIDTH : 320
        SCREEN_HEIGHT : 320
        FPS : 30

        CREDITS: 100
        BET : 10
        PRIZE_ROW : 2

        SYMBOL_SCALE: 3
        SYMBOL_ORIGINAL_WIDTH : 16
        SYMBOL_ORIGINAL_HEIGHT : 16

        REEL_MARGIN: 10
        SYMBOL_MARGIN: 10

        REELS_NUMBER : 3
        REEL_SPEED : 15

        FRAME_CHERRY : 27
        FRAME_WATERMELON : 29
        FRAME_GRAPE : 17
        FRAME_BANANA : 16
        FRAME_PIG : 22
        FRAME_STAR : 30

        SYMBOL_CHERRY : 0
        SYMBOL_WATERMELON : 1
        SYMBOL_GRAPE : 2
        SYMBOL_BANANA : 3
        SYMBOL_PIG : 4
        SYMBOL_STAR : 5

    CONSTANTS.SYMBOL_WIDTH = CONSTANTS.SYMBOL_ORIGINAL_WIDTH * CONSTANTS.SYMBOL_SCALE
    CONSTANTS.SYMBOL_HEIGHT = CONSTANTS.SYMBOL_ORIGINAL_HEIGHT * CONSTANTS.SYMBOL_SCALE

    CONSTANTS.REEL_BASE = [
        CONSTANTS.SYMBOL_CHERRY
        CONSTANTS.SYMBOL_CHERRY
        CONSTANTS.SYMBOL_CHERRY
        CONSTANTS.SYMBOL_WATERMELON
        CONSTANTS.SYMBOL_WATERMELON
        CONSTANTS.SYMBOL_GRAPE
        CONSTANTS.SYMBOL_GRAPE
        CONSTANTS.SYMBOL_BANANA
        CONSTANTS.SYMBOL_PIG
        CONSTANTS.SYMBOL_STAR
    ]

    CONSTANTS.REEL_HEIGHT = CONSTANTS.REEL_BASE.length * (CONSTANTS.SYMBOL_HEIGHT + CONSTANTS.SYMBOL_MARGIN)

    return CONSTANTS